# author: Ole Schuett

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "img_cp2kci_toolbox", "./toolbox/"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["tag", "img_cp2kci_toolbox", "gcr.io/$PROJECT_ID/img_cp2kci_toolbox:$SHORT_SHA"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/img_cp2kci_toolbox:$SHORT_SHA"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["tag", "img_cp2kci_toolbox", "gcr.io/$PROJECT_ID/img_cp2kci_toolbox:latest"]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/img_cp2kci_toolbox:latest"]

#EOF
